services: 
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_MULTIPLE_DATABASES: SoundStreamerDb-Users, SoundStreamerDb-Music, 
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  rabbitmq:
      image: rabbitmq:3-management-alpine
      ports:
        - '5672:5672'
        - '15672:15672'
  
volumes:
  pgdata: